### ISSUE TITLE
Frequently reports incorrect substrings

### ISSUE THREAD

**Issue by connor4312** [elazzabi/longest-common-subsequence#3]
e.g.

```
> require('longest-common-subsequence')('home', 'hello world');
'he'
> require('longest-common-subsequence')('some string', 'nothing common');
'oting'
```

**Comment by elazzabi** [comment]
Hello,
Not sure, but based on the examples you gived, the results are correct.

In fact the result can change depending on which string is used as a base. In this module, the second string is the base.

For the first example, switching the two strings will give you 'ho' instead of 'he'
For the second one, the strings are interchangeable and can be switched and you'll have the same result.

An online demo can be found here: http://lcs-demo.sourceforge.net/

**Comment by connor4312** [comment]
My bad. Wikipedia told me not to confuse them and I still did. Shame on me.

![](https://peet.io/i/17-02-3fcff358-9f0d-44f8-8377-1babae2727b7.png)
